version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '05:00'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: '@types/node'
        versions:
          - 20.10.0
      - dependency-name: husky
        versions:
          - 9.0.11
      - dependency-name: eslint
        versions:
          - 8.0.0
